@startuml

title "인프라 전환 비용 예측"

actor User as EndUser

participant "CM-BUTTERFLY" as butterfly
participant "CM-ANT" as ant
participant "CB-TUMBLEBUG" as tumblebug
participant "CB-SPIDER" as spider


EndUser     -> butterfly ++: 비용 항목 정의/ 설정
    note right
        비용 항목 정의/ 설정
    end note
    butterfly         -> butterfly ++: 비용 항목 관리
        butterfly         -> ant ++: Get : item definition List
        butterfly         <- ant --: return result
        butterfly         -> ant ++: POST : cost item regist
        butterfly         <- ant --: return result
    butterfly        <- butterfly --: return result

    note right
        비용 / 가격 수집
    end note
    ant         -> spider : GET : 가격 조회
    ant         -> spider : GET : 비용 조회
EndUser     <- butterfly --:
    
 EndUser     -> butterfly ++: 비용 항목 정의/ 설정   
    butterfly         -> butterfly ++: 비용 가격 수집
        butterfly         -> tumblebug : GET : MCIS 목록
        butterfly         -> butterfly : VM 선택
        butterfly       -> ant : GET 비용 산정
        
    butterfly        <- butterfly --: return result
EndUser     <- butterfly --:

@enduml
