@startuml

title "인프라 전환 성능 검증"
actor User as EndUser

participant "CM-BUTTERFLY" as butterfly
participant "CM-ANT" as ant
participant "CB-TUMBLEBUG" as tumblebug
participant "CB-SPIDER" as spider

EndUser     -> butterfly ++: 성능 항목 정의/ 설정
    note right
        성능 항목 정의/ 설정
    end note
    butterfly         -> butterfly ++: 성능 항목 관리
        butterfly         -> ant ++: Get : item definition List
        butterfly         <- ant --: return result
        butterfly         -> ant ++: POST : performance item regist
        butterfly         <- ant --: return result
    butterfly        <- butterfly --: return result

    butterfly         -> butterfly ++: 부하 발생환경 구성
        butterfly       -> tumblebug : GET : MCI 목록
        butterfly       -> butterfly : MCI 선택/VM 선택
        butterfly       -> ant : 부하발생 환경 설치 및 구성
        butterfly       -> ant : Get : 부하발생 제어
        
    butterfly        <- butterfly --: return result

    note right
        부하 측정
    end note
    
    butterfly         -> butterfly ++: 부하 측정
        butterfly         -> tumblebug : GET : MCIS 목록
        butterfly         -> butterfly : VM 선택
        butterfly       -> ant : 부하발생
        butterfly         -> ant ++: Get : 성능 분석/평가
        butterfly         <- ant --: return result
    butterfly        <- butterfly --: return result
EndUser     <- butterfly --:

@enduml
